{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "posthog.fullname" . }}
  labels:
    {{- include "_snippet-metadata-labels-common" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dev"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"

spec:
  ingressClassName: posthog-nginx

  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.secretName | default "posthog-dev-tls" }}

  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:

          # =========================
          # EVENTS FIRST (CRITICAL)
          # =========================

          - path: /i
            pathType: Prefix
            backend: &INGESTION
              service:
                name: {{ template "posthog.fullname" . }}-events
                port:
                  number: {{ .Values.service.externalPort }}

          - path: /e
            pathType: Prefix
            backend: *INGESTION

          - path: /capture
            pathType: Prefix
            backend: *INGESTION

          - path: /batch
            pathType: Prefix
            backend: *INGESTION

          - path: /array
            pathType: Prefix
            backend: *INGESTION

          - path: /track
            pathType: Prefix
            backend: *INGESTION

          - path: /engage
            pathType: Prefix
            backend: *INGESTION


          # =========================
          # DECIDE
          # =========================
          {{- if .Values.decide.ingressEnabled }}
          - path: /decide
            pathType: Prefix
            backend:
              service:
                name: {{ template "posthog.fullname" . }}-decide
                port:
                  number: {{ .Values.service.externalPort }}
          {{- end }}


          # =========================
          # RECORDINGS
          # =========================
          {{- if .Values.recordings.ingressEnabled }}
          - path: /s
            pathType: Prefix
            backend:
              service:
                name: {{ template "posthog.fullname" . }}-recordings
                port:
                  number: {{ .Values.service.externalPort }}
          {{- end }}


          # =========================
          # WEB LAST (IMPORTANT)
          # =========================
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "posthog.fullname" . }}-web
                port:
                  number: {{ .Values.service.externalPort }}

{{- end }}
