{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "posthog.fullname" . }}
  labels: {{- include "_snippet-metadata-labels-common" . | nindent 4 }}
  annotations:
    {{- include "_snippet-metadata-annotations-common" . | nindent 4 }}
    {{- if (eq (include "ingress.type" .) "nginx") }}
    kubernetes.io/ingress.class: "nginx"
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}

spec:
  {{- if .Values.ingress.hostname }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
  {{- else }}
  rules:
    - http:
  {{- end }}
        paths:

          # =====================
          # INGESTION ENDPOINTS
          # =====================

          - pathType: Prefix
            path: "/batch"
            backend: &INGESTION
              service:
                name: {{ template "posthog.fullname" . }}-events
                port:
                  number: {{ .Values.service.externalPort }}

          - pathType: Prefix
            path: "/capture/"
            backend: *INGESTION
          - pathType: Exact
            path: "/capture"
            backend: *INGESTION

          - pathType: Prefix
            path: "/decide/"
            backend: *INGESTION
          - pathType: Exact
            path: "/decide"
            backend: *INGESTION

          - pathType: Prefix
            path: "/e/"
            backend: *INGESTION
          - pathType: Exact
            path: "/e"
            backend: *INGESTION

          - pathType: Prefix
            path: "/engage/"
            backend: *INGESTION
          - pathType: Exact
            path: "/engage"
            backend: *INGESTION

          - pathType: Prefix
            path: "/track/"
            backend: *INGESTION
          - pathType: Exact
            path: "/track"
            backend: *INGESTION

          - pathType: Prefix
            path: "/s/"
            backend: *INGESTION
          - pathType: Exact
            path: "/s"
            backend: *INGESTION

          # =====================
          # WEB UI (CATCH-ALL)
          # MUST BE LAST
          # =====================

          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ template "posthog.fullname" . }}-web
                port:
                  number: {{ .Values.service.externalPort }}

  {{- if or (.Values.ingress.secretName) (.Values.ingress.gcp.secretName) }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.secretName | default .Values.ingress.gcp.secretName }}
  {{- end }}

{{- end -}}
